### ISSUE TITLE
Vagrant displaying "The `differencing_disk` configuration option is deprecated and should no longer be used. The `linked_clone` configuration option should be used instead." after using vagrant up

### ISSUE THREAD

**Issue by mrcaron** [chocolatey-community/chocolatey-test-environment#33] opened 2018-12-06 16:49 UTC
I'm using Vagrant 2.2.2 and Hyper-V. When I do a vagrant up, I get a bunch of warning messages 

![image](https://user-images.githubusercontent.com/72183/49598623-a66c2e00-f944-11e8-8a4f-048316db9911.png)

Not sure what this is about...

**Comment by mkevenaar** [comment] 2018-12-06 19:54
Duplicate of #30

**Comment by ferventcoder** [comment] 2018-12-06 21:41
@mkevenaar no such thing as duplicates of pull requests - only issues. My bad for closing this. @franklinyu, can you update your PR to reflect this issue?

**Closed** 2019-07-31 18:32 UTC
Labels: enhancement
